local GameplayConfig = {
    CampRecipe = {
        Wood = 6,
        Cloth = 3,
        Rope = 2,
        Stone = 4,
    },

    Items = {
        Wood = {DisplayName = "Wood", Kind = "Resource", Color = Color3.fromRGB(112, 78, 45)},
        Cloth = {DisplayName = "Cloth", Kind = "Resource", Color = Color3.fromRGB(153, 151, 126)},
        Rope = {DisplayName = "Rope", Kind = "Resource", Color = Color3.fromRGB(142, 111, 67)},
        Stone = {DisplayName = "Stone", Kind = "Resource", Color = Color3.fromRGB(102, 106, 101)},
        Herb = {DisplayName = "Healing Herb", Kind = "Resource", Color = Color3.fromRGB(70, 126, 62)},
        AncientCoin = {DisplayName = "Ancient Coin", Kind = "Valuable", Value = 15, Color = Color3.fromRGB(194, 157, 66)},
        Ruby = {DisplayName = "Ruby", Kind = "Valuable", Value = 120, Color = Color3.fromRGB(151, 38, 46)},
        GoldBar = {DisplayName = "Gold Bar", Kind = "Valuable", Value = 300, Color = Color3.fromRGB(210, 173, 60)},
        RelicShard = {DisplayName = "Relic Shard", Kind = "Valuable", Value = 85, Color = Color3.fromRGB(71, 153, 161)},

        Machete = {DisplayName = "Machete", Kind = "Tool", Damage = 28, Color = Color3.fromRGB(124, 129, 124)},
        Torch = {DisplayName = "Cave Torch", Kind = "Tool", Color = Color3.fromRGB(111, 78, 43)},
        Medkit = {DisplayName = "Medkit", Kind = "ConsumableTool", Heal = 45, Color = Color3.fromRGB(191, 195, 187)},

        BoatRepairKit = {
            DisplayName = "Boat Repair Kit",
            Kind = "Tool",
            Rarity = "Uncommon",
            Description = "Repairs the old raft to Deserted Island.",
            Color = Color3.fromRGB(129, 99, 63),
        },
        ClimbingKit = {
            DisplayName = "Climbing Kit",
            Kind = "Tool",
            Rarity = "Rare",
            Description = "Ropes, anchors and harness needed for Stonefall's upper ridge.",
            Color = Color3.fromRGB(152, 122, 72),
        },
        WinterGear = {
            DisplayName = "Frostpeak Winter Gear",
            Kind = "Tool",
            Rarity = "Epic",
            Description = "Heavy expedition clothing required to survive Frostpeak.",
            Color = Color3.fromRGB(168, 198, 208),
        },
        JaguarTotem = {
            DisplayName = "Jaguar Totem",
            Kind = "Tool",
            Rarity = "Epic",
            Description = "A carved black-stone trophy from the jungle guardian.",
            Color = Color3.fromRGB(62, 68, 64),
        },
        FrostheartRelic = {
            DisplayName = "Frostheart Relic",
            Kind = "Tool",
            Rarity = "Legendary",
            Description = "Legendary treasure taken from the deepest Frostpeak vault.",
            Color = Color3.fromRGB(105, 208, 232),
        },
        ZeroCore = {
            DisplayName = "ZERO Core",
            Kind = "Tool",
            Rarity = "Legendary",
            Description = "A mysterious powered artifact recovered below the bunker.",
            Color = Color3.fromRGB(76, 221, 196),
        },
    },

    Guardians = {
        CaveBoar = {
            DisplayName = "Southern Cave Boar",
            Health = 95,
            Damage = 12,
            WalkSpeed = 12,
            AggroRange = 58,
            AttackRange = 5.5,
            BodyColor = Color3.fromRGB(78, 56, 42),
            AccentColor = Color3.fromRGB(119, 92, 66),
            Scale = 1.0,
        },
        SaltwaterCroc = {
            DisplayName = "Smuggler Crocodile",
            Health = 135,
            Damage = 18,
            WalkSpeed = 9,
            AggroRange = 62,
            AttackRange = 6.5,
            BodyColor = Color3.fromRGB(54, 83, 55),
            AccentColor = Color3.fromRGB(82, 105, 65),
            Scale = 1.2,
        },
        RidgeWolf = {
            DisplayName = "Eastern Ridge Wolf",
            Health = 135,
            Damage = 18,
            WalkSpeed = 16,
            AggroRange = 70,
            AttackRange = 5.2,
            BodyColor = Color3.fromRGB(77, 80, 76),
            AccentColor = Color3.fromRGB(126, 128, 119),
            Scale = 1.0,
        },
        BlackJaguar = {
            DisplayName = "Jungle Black Jaguar",
            Health = 190,
            Damage = 23,
            WalkSpeed = 18,
            AggroRange = 78,
            AttackRange = 5.4,
            BodyColor = Color3.fromRGB(32, 34, 32),
            AccentColor = Color3.fromRGB(64, 69, 62),
            Scale = 1.08,
        },
        FeralHound = {
            DisplayName = "Feral Tunnel Hound",
            Health = 155,
            Damage = 20,
            WalkSpeed = 16,
            AggroRange = 68,
            AttackRange = 5.1,
            BodyColor = Color3.fromRGB(87, 66, 52),
            AccentColor = Color3.fromRGB(139, 108, 79),
            Scale = 0.95,
        },
        IceBear = {
            DisplayName = "Frostpeak Ice Bear",
            Health = 285,
            Damage = 30,
            WalkSpeed = 12,
            AggroRange = 86,
            AttackRange = 7.2,
            BodyColor = Color3.fromRGB(211, 220, 220),
            AccentColor = Color3.fromRGB(164, 190, 198),
            Scale = 1.45,
        },
    },

    RegionProgression = {
        DesertedIsland = {
            Requirement = "BoatRepairKit",
            RequirementName = "Boat Repair Kit",
        },
        StonefallUpper = {
            Requirement = "ClimbingKit",
            RequirementName = "Climbing Kit",
        },
        Frostpeak = {
            Requirement = "WinterGear",
            RequirementName = "Frostpeak Winter Gear",
        },
    },

    CaveRewards = {
        SouthernCliffsCave = {
            ItemId = "BoatRepairKit",
            DisplayName = "Boat Repair Kit",
            Rarity = "Uncommon",
        },
        JungleDepthsCave = {
            ItemId = "ClimbingKit",
            DisplayName = "Climbing Kit",
            Rarity = "Rare",
        },
        EasternForestCave = {
            ItemId = "WinterGear",
            DisplayName = "Frostpeak Winter Gear",
            Rarity = "Epic",
        },
        FrostpeakCave = {
            ItemId = "FrostheartRelic",
            DisplayName = "Frostheart Relic",
            Rarity = "Legendary",
        },
        BunkerServiceTunnel = {
            ItemId = "ZeroCore",
            DisplayName = "ZERO Core",
            Rarity = "Legendary",
        },
    },

    StarterPickups = {
        {Id = "starter_machete", ItemId = "Machete", Amount = 1, Position = Vector3.new(144, 0, 770)},
        {Id = "starter_torch", ItemId = "Torch", Amount = 1, Position = Vector3.new(102, 0, 748)},
        {Id = "starter_wood_a", ItemId = "Wood", Amount = 3, Position = Vector3.new(74, 0, 720)},
        {Id = "starter_wood_b", ItemId = "Wood", Amount = 3, Position = Vector3.new(176, 0, 706)},
        {Id = "starter_cloth", ItemId = "Cloth", Amount = 2, Position = Vector3.new(132, 0, 690)},
        {Id = "starter_rope", ItemId = "Rope", Amount = 1, Position = Vector3.new(190, 0, 735)},
        {Id = "starter_stone", ItemId = "Stone", Amount = 2, Position = Vector3.new(58, 0, 680)},
        {Id = "starter_medkit", ItemId = "Medkit", Amount = 1, Position = Vector3.new(155, 0, 745)},
        {Id = "village_herb", ItemId = "Herb", Amount = 2, Position = Vector3.new(330, 0, 155)},
        {Id = "village_rope", ItemId = "Rope", Amount = 2, Position = Vector3.new(405, 0, 98)},
        {Id = "river_stone", ItemId = "Stone", Amount = 4, Position = Vector3.new(-115, 0, -95)},
        {Id = "east_cloth", ItemId = "Cloth", Amount = 2, Position = Vector3.new(610, 0, 120)},
    },
}

return GameplayConfig
