local GameplayConfig = {
    CampRecipe = {
        Wood = 6,
        Cloth = 3,
        Rope = 2,
        Stone = 4,
    },

    FieldCampRecipe = {
        Wood = 8,
        Cloth = 4,
        Rope = 2,
        Stone = 4,
    },

    Items = {
        Wood = {DisplayName = "Wood", Kind = "Resource", Color = Color3.fromRGB(112, 78, 45)},
        Cloth = {DisplayName = "Cloth", Kind = "Resource", Color = Color3.fromRGB(153, 151, 126)},
        Rope = {DisplayName = "Rope", Kind = "Resource", Color = Color3.fromRGB(142, 111, 67)},
        Stone = {DisplayName = "Stone", Kind = "Resource", Color = Color3.fromRGB(102, 106, 101)},
        Herb = {DisplayName = "Healing Herb", Kind = "Resource", Color = Color3.fromRGB(70, 126, 62)},
        AncientCoin = {DisplayName = "Ancient Coin", Kind = "Valuable", Value = 15, Color = Color3.fromRGB(194, 157, 66)},
        Ruby = {DisplayName = "Ruby", Kind = "Valuable", Value = 120, Color = Color3.fromRGB(151, 38, 46)},
        Emerald = {DisplayName = "Emerald", Kind = "Valuable", Value = 180, Color = Color3.fromRGB(49, 150, 91)},
        Sapphire = {DisplayName = "Sapphire", Kind = "Valuable", Value = 220, Color = Color3.fromRGB(51, 94, 179)},
        Pearl = {DisplayName = "Black Pearl", Kind = "Valuable", Value = 160, Color = Color3.fromRGB(94, 97, 105)},
        GoldBar = {DisplayName = "Gold Bar", Kind = "Valuable", Value = 300, Color = Color3.fromRGB(210, 173, 60)},
        RelicShard = {DisplayName = "Relic Shard", Kind = "Valuable", Value = 85, Color = Color3.fromRGB(71, 153, 161)},
        MapFragment = {DisplayName = "Expedition Map Fragment", Kind = "Valuable", Value = 50, Color = Color3.fromRGB(175, 156, 108)},

        Machete = {DisplayName = "Machete", Kind = "Tool", Damage = 28, AttackRange = 12.5, Color = Color3.fromRGB(124, 129, 124)},
        HunterSpear = {
            DisplayName = "Hunter Spear",
            Kind = "Tool",
            Damage = 40,
            AttackRange = 16,
            Rarity = "Rare",
            Description = "Long-reach jungle weapon recovered from an old hunter cache.",
            Color = Color3.fromRGB(149, 132, 92),
        },
        SteelAxe = {
            DisplayName = "Stonefall Steel Axe",
            Kind = "Tool",
            Damage = 37,
            AttackRange = 12,
            Rarity = "Epic",
            Description = "Heavy expedition axe found high in the Stonefall ruins.",
            Color = Color3.fromRGB(130, 137, 139),
        },
        IcePick = {
            DisplayName = "Frostpeak Ice Pick",
            Kind = "Tool",
            Damage = 48,
            AttackRange = 11,
            Rarity = "Epic",
            Description = "A hardened climbing pick that doubles as a powerful close-range weapon.",
            Color = Color3.fromRGB(142, 187, 204),
        },
        Torch = {DisplayName = "Cave Torch", Kind = "Tool", Color = Color3.fromRGB(111, 78, 43)},
        Medkit = {DisplayName = "Medkit", Kind = "ConsumableTool", Heal = 45, Color = Color3.fromRGB(191, 195, 187)},
        Bandage = {DisplayName = "Field Bandage", Kind = "ConsumableTool", Heal = 24, Color = Color3.fromRGB(216, 210, 190)},

        BoatRepairKit = {
            DisplayName = "Boat Repair Kit",
            Kind = "Tool",
            Rarity = "Uncommon",
            Description = "Repairs the old raft to Deserted Island.",
            Color = Color3.fromRGB(129, 99, 63),
        },
        ClimbingKit = {
            DisplayName = "Climbing Kit",
            Kind = "Tool",
            Rarity = "Rare",
            Description = "Ropes, anchors and harness needed for Stonefall's upper ridge.",
            Color = Color3.fromRGB(152, 122, 72),
        },
        WinterGear = {
            DisplayName = "Frostpeak Winter Gear",
            Kind = "Tool",
            Rarity = "Epic",
            Description = "Heavy expedition clothing required to survive Frostpeak.",
            Color = Color3.fromRGB(168, 198, 208),
        },
        AncientCompass = {
            DisplayName = "Ancient Explorer Compass",
            Kind = "Tool",
            Rarity = "Rare",
            Description = "A weathered expedition compass recovered on Deserted Island.",
            Color = Color3.fromRGB(188, 153, 74),
        },
        JaguarTotem = {
            DisplayName = "Jaguar Totem",
            Kind = "Tool",
            Rarity = "Epic",
            Description = "A carved black-stone trophy from the jungle guardian.",
            Color = Color3.fromRGB(62, 68, 64),
        },
        ExplorerRelic = {
            DisplayName = "Lost Explorer Relic",
            Kind = "Tool",
            Rarity = "Legendary",
            Description = "A legendary relic assembled from clues scattered across the island.",
            Color = Color3.fromRGB(226, 185, 78),
        },
        FrostheartRelic = {
            DisplayName = "Frostheart Relic",
            Kind = "Tool",
            Rarity = "Legendary",
            Description = "Legendary treasure taken from the deepest Frostpeak vault.",
            Color = Color3.fromRGB(105, 208, 232),
        },
        ZeroCore = {
            DisplayName = "ZERO Core",
            Kind = "Tool",
            Rarity = "Legendary",
            Description = "A mysterious powered artifact recovered below the bunker.",
            Color = Color3.fromRGB(76, 221, 196),
        },
    },

    Guardians = {
        CaveBoar = {
            DisplayName = "Southern Cave Boar",
            Health = 95,
            Damage = 12,
            WalkSpeed = 12,
            AggroRange = 58,
            AttackRange = 5.5,
            BodyColor = Color3.fromRGB(78, 56, 42),
            AccentColor = Color3.fromRGB(119, 92, 66),
            Scale = 1.0,
        },
        SaltwaterCroc = {
            DisplayName = "Smuggler Crocodile",
            Health = 135,
            Damage = 18,
            WalkSpeed = 9,
            AggroRange = 62,
            AttackRange = 6.5,
            BodyColor = Color3.fromRGB(54, 83, 55),
            AccentColor = Color3.fromRGB(82, 105, 65),
            Scale = 1.2,
        },
        RidgeWolf = {
            DisplayName = "Eastern Ridge Wolf",
            Health = 135,
            Damage = 18,
            WalkSpeed = 16,
            AggroRange = 70,
            AttackRange = 5.2,
            BodyColor = Color3.fromRGB(77, 80, 76),
            AccentColor = Color3.fromRGB(126, 128, 119),
            Scale = 1.0,
        },
        BlackJaguar = {
            DisplayName = "Jungle Black Jaguar",
            Health = 190,
            Damage = 23,
            WalkSpeed = 18,
            AggroRange = 78,
            AttackRange = 5.4,
            BodyColor = Color3.fromRGB(32, 34, 32),
            AccentColor = Color3.fromRGB(64, 69, 62),
            Scale = 1.08,
        },
        FeralHound = {
            DisplayName = "Feral Tunnel Hound",
            Health = 155,
            Damage = 20,
            WalkSpeed = 16,
            AggroRange = 68,
            AttackRange = 5.1,
            BodyColor = Color3.fromRGB(87, 66, 52),
            AccentColor = Color3.fromRGB(139, 108, 79),
            Scale = 0.95,
        },
        IceBear = {
            DisplayName = "Frostpeak Ice Bear",
            Health = 285,
            Damage = 30,
            WalkSpeed = 12,
            AggroRange = 86,
            AttackRange = 7.2,
            BodyColor = Color3.fromRGB(211, 220, 220),
            AccentColor = Color3.fromRGB(164, 190, 198),
            Scale = 1.45,
        },

        WildBoar = {
            DisplayName = "Wild Boar",
            Health = 58,
            Damage = 8,
            WalkSpeed = 13,
            AggroRange = 44,
            AttackRange = 4.8,
            BodyColor = Color3.fromRGB(83, 61, 45),
            AccentColor = Color3.fromRGB(121, 92, 65),
            Scale = 0.82,
        },
        MarshCroc = {
            DisplayName = "Marsh Crocodile",
            Health = 86,
            Damage = 12,
            WalkSpeed = 9,
            AggroRange = 48,
            AttackRange = 5.8,
            BodyColor = Color3.fromRGB(56, 89, 58),
            AccentColor = Color3.fromRGB(85, 112, 69),
            Scale = 0.92,
        },
        TimberWolf = {
            DisplayName = "Timber Wolf",
            Health = 78,
            Damage = 11,
            WalkSpeed = 17,
            AggroRange = 55,
            AttackRange = 4.8,
            BodyColor = Color3.fromRGB(88, 91, 86),
            AccentColor = Color3.fromRGB(135, 137, 128),
            Scale = 0.82,
        },
        JungleStalker = {
            DisplayName = "Jungle Stalker",
            Health = 108,
            Damage = 16,
            WalkSpeed = 18,
            AggroRange = 60,
            AttackRange = 5.0,
            BodyColor = Color3.fromRGB(38, 43, 37),
            AccentColor = Color3.fromRGB(70, 83, 62),
            Scale = 0.88,
        },
        IceWolf = {
            DisplayName = "Frost Wolf",
            Health = 122,
            Damage = 18,
            WalkSpeed = 18,
            AggroRange = 64,
            AttackRange = 5.2,
            BodyColor = Color3.fromRGB(184, 199, 202),
            AccentColor = Color3.fromRGB(126, 161, 174),
            Scale = 0.92,
        },
    },

    RegionProgression = {
        DesertedIsland = {
            Requirement = "BoatRepairKit",
            RequirementName = "Boat Repair Kit",
        },
        StonefallUpper = {
            Requirement = "ClimbingKit",
            RequirementName = "Climbing Kit",
        },
        Frostpeak = {
            Requirement = "WinterGear",
            RequirementName = "Frostpeak Winter Gear",
        },
    },

    CaveRewards = {
        SouthernCliffsCave = {
            ItemId = "BoatRepairKit",
            DisplayName = "Boat Repair Kit",
            Rarity = "Uncommon",
        },
        JungleDepthsCave = {
            ItemId = "ClimbingKit",
            DisplayName = "Climbing Kit",
            Rarity = "Rare",
        },
        EasternForestCave = {
            ItemId = "WinterGear",
            DisplayName = "Frostpeak Winter Gear",
            Rarity = "Epic",
        },
        FrostpeakCave = {
            ItemId = "FrostheartRelic",
            DisplayName = "Frostheart Relic",
            Rarity = "Legendary",
        },
        BunkerServiceTunnel = {
            ItemId = "ZeroCore",
            DisplayName = "ZERO Core",
            Rarity = "Legendary",
        },
    },

    WorldChests = {
        {Id = "beach_wreck_1", Position = Vector3.new(210, 0, 720), Tier = "Supplies", Rarity = "Common"},
        {Id = "beach_wreck_2", Position = Vector3.new(-40, 0, 740), Tier = "Supplies", Rarity = "Common"},
        {Id = "beach_rocks", Position = Vector3.new(330, 0, 650), Tier = "Relic", Rarity = "Uncommon"},
        {Id = "plains_banyan", Position = Vector3.new(-20, 0, 315), Tier = "Supplies", Rarity = "Common"},
        {Id = "plains_bluehole", Position = Vector3.new(145, 0, -250), Tier = "Relic", Rarity = "Uncommon"},
        {Id = "plains_oldroad", Position = Vector3.new(285, 0, 35), Tier = "Supplies", Rarity = "Common"},
        {Id = "village_store", Position = Vector3.new(390, 0, 145), Tier = "Relic", Rarity = "Uncommon"},
        {Id = "village_hidden", Position = Vector3.new(430, 0, 65), Tier = "Deep", Rarity = "Rare"},
        {Id = "jungle_camp", Position = Vector3.new(-360, 0, 340), Tier = "Supplies", Rarity = "Common"},
        {Id = "jungle_shrine", Position = Vector3.new(-285, 0, 95), Tier = "Relic", Rarity = "Rare"},
        {Id = "jungle_ravine", Position = Vector3.new(-560, 0, 40), Tier = "Deep", Rarity = "Rare"},
        {Id = "jungle_mangrove", Position = Vector3.new(-820, 0, 230), Tier = "Relic", Rarity = "Uncommon"},
        {Id = "jungle_north", Position = Vector3.new(-610, 0, -145), Tier = "Deep", Rarity = "Rare"},
        {Id = "south_tidepool", Position = Vector3.new(720, 0, 630), Tier = "Relic", Rarity = "Uncommon"},
        {Id = "south_forest", Position = Vector3.new(500, 0, 440), Tier = "Supplies", Rarity = "Common"},
        {Id = "south_cliff", Position = Vector3.new(320, 0, 570), Tier = "Deep", Rarity = "Rare"},
        {Id = "east_supply", Position = Vector3.new(585, 0, 115), Tier = "Supplies", Rarity = "Common"},
        {Id = "east_watch", Position = Vector3.new(825, 0, -230), Tier = "Relic", Rarity = "Rare"},
        {Id = "east_arch", Position = Vector3.new(890, 0, -540), Tier = "Deep", Rarity = "Rare"},
        {Id = "east_bunker", Position = Vector3.new(820, 0, -55), Tier = "Deep", Rarity = "Rare"},
        {Id = "stonefall_low", Position = Vector3.new(130, 0, -430), Tier = "Relic", Rarity = "Rare"},
        {Id = "stonefall_ruins", Position = Vector3.new(275, 0, -515), Tier = "Deep", Rarity = "Epic"},
        {Id = "stonefall_ridge", Position = Vector3.new(380, 0, -600), Tier = "Deep", Rarity = "Epic"},
        {Id = "frost_gate", Position = Vector3.new(-120, 0, -510), Tier = "Relic", Rarity = "Rare"},
        {Id = "frost_shelf", Position = Vector3.new(-275, 0, -650), Tier = "Deep", Rarity = "Epic"},
        {Id = "frost_high", Position = Vector3.new(-80, 0, -790), Tier = "Deep", Rarity = "Epic"},
        {Id = "deserted_beach", Position = Vector3.new(-1190, 18, 690), FixedY = 18, Tier = "Supplies", Rarity = "Uncommon"},
        {Id = "deserted_shelter", Position = Vector3.new(-1260, 25, 690), FixedY = 25, Tier = "Relic", Rarity = "Rare"},
        {Id = "deserted_north", Position = Vector3.new(-1315, 24, 625), FixedY = 24, Tier = "Deep", Rarity = "Epic"},
        {Id = "deserted_south", Position = Vector3.new(-1225, 22, 760), FixedY = 22, Tier = "Deep", Rarity = "Epic"},
    },

    SpecialCaches = {
        {Id = "HunterSpearCache", CaveId = "AdventureHunterSpear", Position = Vector3.new(-455, 0, 245), ItemId = "HunterSpear", DisplayName = "Hunter Spear", Rarity = "Rare"},
        {Id = "SteelAxeCache", CaveId = "AdventureSteelAxe", Position = Vector3.new(310, 0, -535), ItemId = "SteelAxe", DisplayName = "Stonefall Steel Axe", Rarity = "Epic"},
        {Id = "IcePickCache", CaveId = "AdventureIcePick", Position = Vector3.new(-205, 0, -690), ItemId = "IcePick", DisplayName = "Frostpeak Ice Pick", Rarity = "Epic"},
        {Id = "CompassCache", CaveId = "AdventureCompass", Position = Vector3.new(-1260, 27, 705), FixedY = 27, ItemId = "AncientCompass", DisplayName = "Ancient Explorer Compass", Rarity = "Rare"},
        {Id = "ExplorerRelicCache", CaveId = "AdventureExplorerRelic", Position = Vector3.new(-260, 0, 80), ItemId = "ExplorerRelic", DisplayName = "Lost Explorer Relic", Rarity = "Legendary"},
    },

    FieldCamps = {
        {Id = "CentralPlainsCamp", Position = Vector3.new(85, 0, 245)},
        {Id = "JungleBaseCamp", Position = Vector3.new(-435, 0, 365)},
        {Id = "EasternShoreCamp", Position = Vector3.new(690, 0, 260)},
        {Id = "StonefallCamp", Position = Vector3.new(95, 0, -390)},
        {Id = "DesertedIslandCamp", Position = Vector3.new(-1210, 22, 720), FixedY = 22},
    },

    WorldEncounters = {
        {Id = "boar_plains_a", Position = Vector3.new(-70, 0, 410), Type = "WildBoar"},
        {Id = "boar_plains_b", Position = Vector3.new(250, 0, 300), Type = "WildBoar"},
        {Id = "jungle_stalker_a", Position = Vector3.new(-485, 0, 300), Type = "JungleStalker"},
        {Id = "jungle_stalker_b", Position = Vector3.new(-690, 0, 120), Type = "JungleStalker"},
        {Id = "marsh_croc_a", Position = Vector3.new(-650, 0, 260), Type = "MarshCroc"},
        {Id = "marsh_croc_b", Position = Vector3.new(-830, 0, 220), Type = "MarshCroc"},
        {Id = "east_wolf_a", Position = Vector3.new(650, 0, -90), Type = "TimberWolf"},
        {Id = "east_wolf_b", Position = Vector3.new(760, 0, -320), Type = "TimberWolf"},
        {Id = "stonefall_wolf_a", Position = Vector3.new(175, 0, -470), Type = "TimberWolf"},
        {Id = "stonefall_wolf_b", Position = Vector3.new(365, 0, -560), Type = "TimberWolf"},
        {Id = "frost_wolf_a", Position = Vector3.new(-275, 0, -590), Type = "IceWolf"},
        {Id = "frost_wolf_b", Position = Vector3.new(-90, 0, -720), Type = "IceWolf"},
        {Id = "frost_wolf_c", Position = Vector3.new(-20, 0, -820), Type = "IceWolf"},
        {Id = "deserted_boar", Position = Vector3.new(-1290, 24, 735), FixedY = 24, Type = "WildBoar"},
    },

    StarterPickups = {
        {Id = "starter_machete", ItemId = "Machete", Amount = 1, Position = Vector3.new(144, 0, 770)},
        {Id = "starter_torch", ItemId = "Torch", Amount = 1, Position = Vector3.new(102, 0, 748)},
        {Id = "starter_wood_a", ItemId = "Wood", Amount = 3, Position = Vector3.new(74, 0, 720)},
        {Id = "starter_wood_b", ItemId = "Wood", Amount = 3, Position = Vector3.new(176, 0, 706)},
        {Id = "starter_cloth", ItemId = "Cloth", Amount = 2, Position = Vector3.new(132, 0, 690)},
        {Id = "starter_rope", ItemId = "Rope", Amount = 1, Position = Vector3.new(190, 0, 735)},
        {Id = "starter_stone", ItemId = "Stone", Amount = 2, Position = Vector3.new(58, 0, 680)},
        {Id = "starter_medkit", ItemId = "Medkit", Amount = 1, Position = Vector3.new(155, 0, 745)},
        {Id = "starter_bandage", ItemId = "Bandage", Amount = 1, Position = Vector3.new(118, 0, 718)},
        {Id = "village_herb", ItemId = "Herb", Amount = 2, Position = Vector3.new(330, 0, 155)},
        {Id = "village_rope", ItemId = "Rope", Amount = 2, Position = Vector3.new(405, 0, 98)},
        {Id = "river_stone", ItemId = "Stone", Amount = 4, Position = Vector3.new(-115, 0, -95)},
        {Id = "east_cloth", ItemId = "Cloth", Amount = 2, Position = Vector3.new(610, 0, 120)},
        {Id = "map_fragment_beach", ItemId = "MapFragment", Amount = 1, Position = Vector3.new(280, 0, 680)},
        {Id = "map_fragment_jungle", ItemId = "MapFragment", Amount = 1, Position = Vector3.new(-280, 0, 80)},
        {Id = "map_fragment_stonefall", ItemId = "MapFragment", Amount = 1, Position = Vector3.new(250, 0, -500)},
        {Id = "map_fragment_deserted", ItemId = "MapFragment", Amount = 1, Position = Vector3.new(-1240, 25, 720)},
    },
}

return GameplayConfig
