local WorldConfig = {
    WorldVersion = 8,
    Seed = 7102026,

    SeaLevel = 0,
    OceanDepth = 90,
    WorldHalfSize = 1750,

    Island = {
        HalfX = 1180,
        HalfZ = 980,
        Grid = 12,
        BaseY = -72,
        BeachBand = 0.34,
    },

    Generation = {
        YieldEvery = 160,
        ClearExisting = true,
        VegetationDensity = 1.0,
    },

    Vegetation = {
        JungleTreeTarget = 2850,
        PalmTarget = 460,
        MangroveTarget = 300,
        UnderstoryTarget = 1550,
        RockTarget = 300,
        MaxAttemptsMultiplier = 7,
        TreeSpacing = 8.5,
        PalmSpacing = 10,
        MangroveSpacing = 7.5,
        PathClearance = 9,
        ForestNoiseScale = 185,
        ForestNoiseBias = -0.34,
        MaxTreeElevation = 250,
    },

    Regions = {
        ShipwreckBeach = {
            DisplayName = "SHIPWRECK BEACH",
            Center = Vector3.new(120, 0, 760),
            Radius = 330,
            Difficulty = 1,
        },
        CentralPlains = {
            DisplayName = "CENTRAL PLAINS",
            Center = Vector3.new(80, 0, 90),
            Radius = 360,
            Difficulty = 1,
        },
        JungleDepths = {
            DisplayName = "JUNGLE DEPTHS",
            Center = Vector3.new(-610, 0, 230),
            Radius = 370,
            Difficulty = 2,
        },
        SouthernForest = {
            DisplayName = "SOUTHERN FOREST",
            Center = Vector3.new(470, 0, 455),
            Radius = 330,
            Difficulty = 2,
        },
        EasternShores = {
            DisplayName = "EASTERN SHORES",
            Center = Vector3.new(860, 0, 180),
            Radius = 320,
            Difficulty = 2,
        },
        StonefallRuins = {
            DisplayName = "STONEFALL RUINS",
            Center = Vector3.new(260, 0, -515),
            Radius = 250,
            Difficulty = 3,
            Requirement = "ClimbingKit",
            RequirementName = "Climbing Kit",
        },
        Frostpeak = {
            DisplayName = "FROSTPEAK MOUNTAINS",
            Center = Vector3.new(-150, 0, -690),
            Radius = 390,
            Difficulty = 5,
            Requirement = "WinterGear",
            RequirementName = "Frostpeak Winter Gear",
        },
        DesertedIsland = {
            DisplayName = "DESERTED ISLAND",
            Center = Vector3.new(-1260, 0, 690),
            Radius = 150,
            Difficulty = 3,
            Requirement = "BoatRepairKit",
            RequirementName = "Boat Repair Kit",
        },
    },

    Waterways = {
        MainRiver = {
            Vector3.new(-95, 0, -500),
            Vector3.new(-125, 0, -430),
            Vector3.new(-160, 0, -350),
            Vector3.new(-210, 0, -270),
            Vector3.new(-255, 0, -205),
            Vector3.new(-260, 0, -145),
            Vector3.new(-320, 0, -65),
            Vector3.new(-400, 0, 25),
            Vector3.new(-490, 0, 115),
            Vector3.new(-600, 0, 205),
            Vector3.new(-730, 0, 265),
            Vector3.new(-875, 0, 315),
            Vector3.new(-1035, 0, 355),
        },
        RiverWidth = 26,
        RiverDepth = 8,
        RiverBankBlend = 68,
        PoolCenter = Vector3.new(-275, 0, -115),
        PoolRadius = 52,
        PoolDepth = 11,
    },

    Exploration = {
        Caves = {
            SouthernCliffsCave = {
                DiscoveryName = "Southern Cliffs Cave",
                Entrance = Vector3.new(270, 0, 600),
                Nodes = {
                    Vector3.new(270, -4, 600),
                    Vector3.new(240, -16, 560),
                    Vector3.new(205, -30, 520),
                    Vector3.new(170, -44, 480),
                    Vector3.new(130, -55, 440),
                    Vector3.new(90, -62, 400),
                },
                TunnelRadius = 14,
                ChamberRadius = 29,
                ClearingRadius = 34,
                Props = "Expedition",
                Guardian = "CaveBoar",
                Difficulty = 1,
            },
            JungleDepthsCave = {
                DiscoveryName = "Jungle Depths Cave",
                Entrance = Vector3.new(-620, 0, 205),
                Nodes = {
                    Vector3.new(-620, -5, 205),
                    Vector3.new(-585, -18, 165),
                    Vector3.new(-545, -34, 120),
                    Vector3.new(-505, -50, 75),
                    Vector3.new(-462, -66, 30),
                    Vector3.new(-420, -76, -10),
                },
                TunnelRadius = 14,
                ChamberRadius = 30,
                ClearingRadius = 36,
                Props = "Natural",
                Guardian = "BlackJaguar",
                Difficulty = 3,
            },
            EasternForestCave = {
                DiscoveryName = "Eastern Forest Cave",
                Entrance = Vector3.new(650, 0, 120),
                Nodes = {
                    Vector3.new(650, -4, 120),
                    Vector3.new(615, -16, 80),
                    Vector3.new(575, -30, 38),
                    Vector3.new(535, -44, -5),
                    Vector3.new(495, -58, -48),
                    Vector3.new(450, -68, -90),
                },
                TunnelRadius = 14,
                ChamberRadius = 29,
                ClearingRadius = 34,
                Props = "Expedition",
                Guardian = "RidgeWolf",
                Difficulty = 3,
            },
            FrostpeakCave = {
                DiscoveryName = "Frostpeak Ice Cavern",
                Entrance = Vector3.new(-250, 0, -610),
                Nodes = {
                    Vector3.new(-250, -6, -610),
                    Vector3.new(-220, -20, -650),
                    Vector3.new(-185, -38, -690),
                    Vector3.new(-145, -58, -730),
                    Vector3.new(-100, -80, -760),
                    Vector3.new(-55, -98, -785),
                },
                TunnelRadius = 16,
                ChamberRadius = 34,
                ClearingRadius = 38,
                Props = "Natural",
                Guardian = "IceBear",
                Difficulty = 5,
                RequiredItem = "WinterGear",
            },
            BunkerServiceTunnel = {
                DiscoveryName = "Service Tunnel 03",
                Entrance = Vector3.new(900, 0, 45),
                Nodes = {
                    Vector3.new(900, -4, 45),
                    Vector3.new(875, -14, 20),
                    Vector3.new(850, -26, -8),
                    Vector3.new(825, -38, -36),
                    Vector3.new(800, -48, -68),
                    Vector3.new(775, -54, -100),
                },
                TunnelRadius = 12,
                ChamberRadius = 23,
                ClearingRadius = 27,
                Props = "Bunker",
                Guardian = "FeralHound",
                Difficulty = 4,
            },
        },

        Sites = {
            AbandonedCamp = {
                DiscoveryName = "Abandoned Jungle Camp",
                Kind = "Camp",
                Position = Vector3.new(-360, 0, 340),
                Radius = 45,
            },
            AncientCircle = {
                DiscoveryName = "Ancient Circle",
                Kind = "Shrine",
                Position = Vector3.new(-260, 0, 80),
                Radius = 42,
            },
            ExpeditionRemains = {
                DiscoveryName = "Expedition Remains",
                Kind = "Expedition",
                Position = Vector3.new(-470, 0, -245),
                Radius = 30,
            },
            SupplyCache = {
                DiscoveryName = "Weathered Supply Cache",
                Kind = "Cache",
                Position = Vector3.new(585, 0, 120),
                Radius = 28,
            },
            MangroveDock = {
                DiscoveryName = "Old Mangrove Dock",
                Kind = "Dock",
                Position = Vector3.new(-865, 0, 285),
                Radius = 44,
            },
            CliffOverlook = {
                DiscoveryName = "Old Watchtower Overlook",
                Kind = "Overlook",
                Position = Vector3.new(830, 0, -230),
                Radius = 34,
            },
            TidePools = {
                DiscoveryName = "South Tide Pools",
                Kind = "TidePools",
                Position = Vector3.new(720, 0, 630),
                Radius = 42,
            },
        },

        Signposts = {
            {
                Name = "ShipwreckTrailSign",
                Position = Vector3.new(95, 0, 610),
                Yaw = -12,
                Lines = {"CENTRAL PLAINS  >", "<  SHIPWRECK BEACH"},
            },
            {
                Name = "CentralCrossroadsSign",
                Position = Vector3.new(300, 0, 180),
                Yaw = 16,
                Lines = {"<  JUNGLE DEPTHS", "EASTERN SHORES  >", "STONEFALL  >"},
            },
            {
                Name = "RiverTrailSign",
                Position = Vector3.new(-145, 0, -105),
                Yaw = -28,
                Lines = {"<  WATERFALL", "FROSTPEAK  ^", "CENTRAL PLAINS  >"},
            },
            {
                Name = "EastTrailSign",
                Position = Vector3.new(710, 0, 75),
                Yaw = 34,
                Lines = {"BUNKER  >", "OLD WATCHTOWER  >", "<  CENTRAL PLAINS"},
            },
            {
                Name = "JungleTrailSign",
                Position = Vector3.new(-520, 0, 360),
                Yaw = -48,
                Lines = {"JUNGLE DEPTHS  >", "OLD DOCK  >", "<  SHIPWRECK BEACH"},
            },
            {
                Name = "StonefallTrailSign",
                Position = Vector3.new(55, 0, -495),
                Yaw = 8,
                Lines = {"STONEFALL RUINS  >", "FROSTPEAK  >", "<  RIVER"},
            },
            {
                Name = "FrostpeakWarningSign",
                Position = Vector3.new(-115, 0, -470),
                Yaw = 0,
                Lines = {"FROSTPEAK", "WINTER GEAR REQUIRED"},
            },
        },
    },

    Audit = {
        WarnPathGrade = 0.65,
        WarnGeneratedDescendants = 22000,
        MaxGeneratedDescendants = 34000,
        MinTreeCount = 3000,
    },

    Locations = {
        CrashBeach = Vector3.new(120, 8, 790),
        JungleGate = Vector3.new(90, 36, 560),
        Village = Vector3.new(360, 52, 120),
        RiverBasin = Vector3.new(-180, 46, 120),
        Waterfall = Vector3.new(-260, 92, -130),
        BunkerApproach = Vector3.new(820, 88, -50),
        EastLookout = Vector3.new(930, 150, -250),
        RidgeRuins = Vector3.new(260, 205, -515),
        Summit = Vector3.new(-150, 300, -690),
        Mangroves = Vector3.new(-780, 18, 200),
        DesertedIsland = Vector3.new(-1260, 12, 690),
    },

    ScenicZones = {
        AncientBanyan = {
            Position = Vector3.new(-40, 0, 330),
            Radius = 86,
        },
        BlueHole = {
            Position = Vector3.new(80, 0, -300),
            Radius = 72,
        },
        MangroveLagoon = {
            Position = Vector3.new(-875, 0, 250),
            Radius = 62,
        },
        WindArch = {
            Position = Vector3.new(900, 0, -575),
            Radius = 78,
        },
    },

    Paths = {
        Main = {
            Vector3.new(120, 0, 760),
            Vector3.new(80, 0, 610),
            Vector3.new(180, 0, 480),
            Vector3.new(310, 0, 320),
            Vector3.new(360, 0, 140),
            Vector3.new(270, 0, -20),
            Vector3.new(80, 0, -90),
            Vector3.new(-120, 0, -140),
            Vector3.new(-260, 0, -140),
            Vector3.new(-150, 0, -330),
            Vector3.new(40, 0, -480),
            Vector3.new(260, 0, -530),
            Vector3.new(40, 0, -650),
            Vector3.new(-150, 0, -700),
        },
        EastLoop = {
            Vector3.new(360, 0, 120),
            Vector3.new(540, 0, 160),
            Vector3.new(720, 0, 80),
            Vector3.new(820, 0, -40),
            Vector3.new(860, 0, -210),
            Vector3.new(700, 0, -360),
            Vector3.new(470, 0, -430),
            Vector3.new(260, 0, -515),
        },
        WestLoop = {
            Vector3.new(90, 0, 610),
            Vector3.new(-150, 0, 650),
            Vector3.new(-390, 0, 570),
            Vector3.new(-620, 0, 400),
            Vector3.new(-790, 0, 200),
            Vector3.new(-610, 0, 20),
            Vector3.new(-400, 0, -60),
            Vector3.new(-220, 0, -120),
        },
    },
}

return WorldConfig
